layout_spectrum: 0.6225932540837675
typography_spectrum: 0.4575569196604192
color:
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
  brandStrength: 0.7986726115923375
  lightness: 0.9706925994250923
  saturation: 0.7219404452480376
  rhythmicContrast: 0.828783371951431
name: Construction
favicon: null
title: Construction pictures and news
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
