name: Construction
favicon: null
layout_spectrum: 0.50335
typography_spectrum: 0.76034
title: Construction pictures and news
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9bb9ad'
    - '#ffffff'
    - '#464145'
    - '#74757a'
    - '#c4dfd6'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
