layout_spectrum: 0.03451349725946784
typography_spectrum: 0.11026717838831246
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.9974767495878041
  lightness: 0.3610717379488051
  saturation: 0.34354725386947393
  rhythmicContrast: 0.06022199196740985
name: Construction
favicon: null
title: Construction pictures and news
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
